### ISSUE TITLE
Server Crash - Line 47

### ISSUE THREAD

**Issue by ItzBecky** [JackNoordhuis/DiscordRelay-PocketMine#5]
Line 47 of AutoloaderLoader crashes the server can this be sorted please
[Fri_Jun_14-17.24.52-UTC_2019.log](https://github.com/JackNoordhuis/DiscordRelay-PocketMine/files/3293172/Fri_Jun_14-17.24.52-UTC_2019.log)

**Comment by JackNoordhuis** [comment]
Don't run from source unless you know what you're doing. https://github.com/JackNoordhuis/DiscordRelay-PocketMine#download
